apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eo26opg3v-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:958abf0fe6844efb9ade7733abed3d88fb436b3c@sha256:f646bd0d0106eac176fcb79e9a7c1486655409fbd6b7baea397a9f88f2897c11
          name: container-image
